import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
    paddingTop: 50,
  },
  header: {
    fontSize: 28,
    fontWeight: "800",
    color: "#fff",
    marginVertical: 24,
    paddingLeft: 24,
    borderLeftWidth: 6,
    borderLeftColor: "#1E90FF",
    letterSpacing: 1.5,
  },
  tollsList: {
    paddingHorizontal: 28,
  },
  tollCard: {
    backgroundColor: "rgba(45, 45, 45, 0.85)", 
    borderRadius: 32, 
    overflow: "hidden",
    marginBottom: 22, 
    position: "relative",
    paddingBottom: 16, 
    shadowColor: "rgba(0, 0, 0, 0.8)", 
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 14,
    elevation: 14, 
    borderWidth: 1.2, 
    borderColor: "rgba(255, 255, 255, 0.06)", 
    backdropFilter: "blur(14px)", 
  },
  tollImage: {
    width: "100%",
    height: 190, 
    borderRadius: 32,
  },
  tollName: {
    position: "absolute",
    top: 16,
    left: 24,
    color: "#fff",
    fontSize: 22, 
    fontWeight: "bold",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    textShadowColor: "rgba(0, 0, 0, 0.6)",
    textShadowOffset: { width: 2, height: 3 },
    textShadowRadius: 6,
  },
  qrContainer: {
    position: "absolute",
    bottom: 14, 
    left: 18, 
    backgroundColor: "rgba(255, 255, 255, 0.9)", 
    padding: 9, 
    borderRadius: 14, 
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 7,
    elevation: 9, 
  },
  qrCode: {
    width: 50, 
    height: 50,
  },
  navigateButton: {
    position: "absolute",
    top: "50%",
    right: 5,  // ✅ Shifted the button slightly to the **left**
    backgroundColor: "#1E90FF", 
    borderRadius: 45,  
    width: 50,  
    height: 50,  
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "rgba(0, 0, 0, 0.7)", 
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 12,
    borderWidth: 3,  
    borderColor: "#1E90FF",
  },
  navigateIcon: {
    fontSize: 24, 
    color: "#FFF",
    fontWeight: "bold",
  },
});
